### ISSUE TITLE
update to newer lalrpop version

### ISSUE THREAD

**Issue by TECHNOFAB11** [Aelto/surreal-simple-querybuilder#11]
The current version cannot parse "in" for example which makes it harder to manually handle the graph relation tables (which have at least in, out, id). I think the next version after the currently used one supports it already

Escaping like r#in etc does not work either currently

**Comment by Aelto** [comment]
Hi, sure of course! Could you provide me a quick snippet of what you're trying to parse but cannot at the moment? That would help me understand exactly what additional things i should parse

**Comment by TECHNOFAB11** [comment]
Thanks, of course here is a small snippet:

```rust
model!(relation {
    id,
    pub in, // this does not work currently
    pub out,
    pub some_data,
})
```

I could not figure out how to escape the in, the newer lalrpop parser should allow using this for example (or maybe also just "in"?):

```rust
...
    pub r#in,
...
```

**Comment by Aelto** [comment]
Thanks for the snippet. I've opted to supporting the raw literal operator `r#`. You can see a usage example from this [unit test](https://github.com/Aelto/surreal-simple-querybuilder/blob/master/tests/model.rs) if you wish.

Requiring an explicity `r#` allowed me to:
- follow the rust syntax we're used to, keeping the macro intuitive
- while also leaving the `r#` out of the deserialized result so that it doesn't get in our queries
```rs
assert_eq!(schema::model.r#in.to_string(), "in");
```

**Comment by TECHNOFAB11** [comment]
> Thanks for the snippet. I've opted to supporting the raw literal operator `r#`. You can see a usage example from this [unit test](https://github.com/Aelto/surreal-simple-querybuilder/blob/master/tests/model.rs) if you wish.
> 
> Requiring an explicity `r#` allowed me to:
> - follow the rust syntax we're used to, keeping the macro intuitive
> - while also leaving the `r#` out of the deserialized result so that it doesn't get in our queries
> ```rs
> assert_eq!(schema::model.r#in.to_string(), "in");
> ```
> 
> EDIT: you may find these changes in the [v0.8.1](https://crates.io/crates/surreal-simple-querybuilder/0.8.1) i just published to crates.io

That was fast, thanks a lot! 🙂
